export const state = {
	score: 0,
	spawnIntervalUpgrades: 0,
	squareBuffUpgrades: 0,
	triangleBuffUpgrades: 0,
	shinyChanceUpgrades: 0,
	eggEvoTimeUpgrades: 0,
	squareEvoTimeUpgrades: 0,
	triangleEvoTimeUpgrades: 0,
	pentagonBuffUpgrades: 0,
	pentagonEvoTimeUpgrades: 0,
	hexagonBuffUpgrades: 0,
	hexagonEvoTimeUpgrades: 0,
	arenaFovUpgrades: 0,
	tankCount: 0,
	tankReloadUpgrades: 0,
	tankDamageUpgrades: 0,
	tankHealthUpgrades: 0,
	tankSpeedUpgrades: 0,
	tankRarityCap: 4,
	shapeDeathAnimEnabled: true,
	bulletDeathAnimEnabled: true,
	rarityCap: 0,
	shapesSpawnInterval: 2000,
	shapeTypeBuff: 1,
	shapeRarityBuff: 1,
	shapeEvoNerf: { 0: 1, 1: 1, 2: 1, 3: 1, 4: 1, 5: 1, 6: 1, 7: 1 },
	layersBuff: 0,
	shapesCap: 10,
	layersCaps: { 0: 1, 1: 1, 2: 1, 3: 1, 4: 1, 5: 1, 6: 1, 7: 1 },
	squaresUnlocked: false,
	trianglesUnlocked: false,
	pentagonsUnlocked: false,
	hexagonsUnlocked: false,
};
